### ISSUE TITLE
Message Numbering change deletes entire thread

### ISSUE THREAD

**Issue by larisa-a-white** [simonetthomas/Blue_Thread#59]
**Describe the bug**
Created a 7-post thread, with pictures, and alt-text, using the +/- buttons below each post to generate the new one, and typing directly into the smaller boxes for each post -- rather than typing into the big box on the left, which disallows photos.

Just before posting, I noticed that the first one (only) had a (1/1) numbering at the bottom. To remove that number, I toggled the Numbering pull-down menu to remove the message numbering from the thread, and the entire thread disappeared. An hour of careful work. Gone.

**Comment by simonetthomas** [comment]
Thank you for your input. I understand your experience has been frustrating, but this is not really a bug, but rather the fact you used Blue Thread in a way that was not intended.

Ideally you're supposed to type the text in the left box, you can still add photos to each post in the boxes in the right after that. Changing the numbering separates the text again into multiple posts based on what's in the big box, that's why your posts disappeared. 

You can still add/remove posts and edit the texts on the right, but changing what's in the left box will always replace them, so editing on the right should mainly be used to edit small things rather than type all the thread.

Hope that helps
